.TH ROKUREMOTE 1 LOCAL

.SH NAME

rokuremote - a remote control for your roku

.SH DESCRIPTION

rokuremote is a remote control for your Roku. Enter the IP address and navigate
.P
Thank you to giuspec-x-osk http://code.google.com/p/giuspen-x-osk/ for providing a nice keyboard layouy, which I used for the keyboard in this application
.P
License is GNU GPL v3
.P
Hotkeys:
.br
ctrl-w - up
.br
ctrl-a - left
.br
ctrl-s - down
.br
ctrl-d - right
.br
ctrl-q - back
.br
ctrl-e - select
.br
shift-r - replay
.br
ctrl-i - info
.br
ctrl-r - rewind
.br 
ctrl-p / ctrl-v - pause
.br
ctrl-f - fast forward
.br
k - keyboard
.P
On the keyboard:
.br
ctrl-c - close
.br
ctrl-e - select
.br
ctrl-w - up
.br
ctrl-a - left
.br
ctrl-s - down
.br
ctrl-d - right

.SH OPTIONS
No command line options

.SH AUTHOR

Jason Montleon <jason@montleon.com>

